config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "sessions"
  }

  root "landing#index"
  get "/update_strava", to: "landing#update_strava"

  resources :competitions, only: %i[show]

  resource :account, only: %i[edit update]

  namespace :admin do
    root to: "competition_users#index"
    resources :competitions, only: %i[index new create]
    resources :competition_users, only: %i[index edit update]
  end

  mount Lookbook::Engine, at: "/lookbook"

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @competition = Competition.current || Competition.create(start_date: Date.parse("2024-5-1"))
    @competition_users = @competition.competition_users_included
      .includes(:user, :competition_activities).score_ordered
    @page_title = "May is Bike Month"
    @previous_competitions = Competition.where.not(id: @competition.id).order(start_date: :desc)
    @skip_wrapper_class = true
  end

  def update_strava
    if UpdateCompetitionUserJob.enqueue_current
      render json: {message: "success"}
    else
      render json: {message: "No current competition!"}
    end
  end
end

app/views/landing/index.html.erb
<%= render partial: "/competitions/show_competition" %>

<script>
  window.shouldUpdateStravaInBackground = true
</script>

<% if @previous_competitions.any? %>
  <div class="wrapper-class pt-2!">
    <p class="">
      View results from:
      <%= @previous_competitions.map do |competition|
          link_to(competition.year, competition_path(competition.slug), class: "base-link")
        end.to_sentence.html_safe %>
    </p>
  </div>
<% end %>