config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "sessions"
  }

  root "landing#index"
  get "/update_strava", to: "landing#update_strava"

  resources :competitions, only: %i[show]

  resource :account, only: %i[edit update]

  namespace :admin do
    root to: "competition_users#index"
    resources :competitions, only: %i[index new create]
    resources :competition_users, only: %i[index edit update]
  end

  mount Lookbook::Engine, at: "/lookbook"

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/competition_user.rb
# == Schema Information
#
# Table name: competition_users
#
#  id                      :bigint           not null, primary key
#  display_name            :text
#  included_activity_types :jsonb
#  included_in_competition :boolean          default(FALSE), not null
#  score                   :decimal(, )
#  score_data              :jsonb
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  competition_id          :bigint
#  user_id                 :bigint
#
# Indexes
#
#  index_competition_users_on_competition_id  (competition_id)
#  index_competition_users_on_user_id         (user_id)
#
class CompetitionUser < ApplicationRecord
  BLANK_SCORE = {dates: [], distance: 0, elevation: 0}.freeze
  belongs_to :competition
  belongs_to :user

  has_many :competition_activities
  has_many :competition_activities_included, -> { included_in_competition },
    class_name: "CompetitionActivity"
  has_many :competition_activities_excluded, -> { excluded_from_competition },
    class_name: "CompetitionActivity"

  before_validation :set_calculated_attributes
  validates_uniqueness_of :user_id, scope: [:competition_id], allow_nil: false

  scope :current_competition, -> { joins(:competition).where(competitions: {current: true}) }
  scope :included_in_competition, -> { where(included_in_competition: true) }
  scope :excluded_from_competition, -> { where(included_in_competition: false) }
  scope :included_in_current_competition, -> { included_in_competition.current_competition }
  scope :score_ordered, -> { reorder(score: :desc) }

  class << self
    def score_for(dates:, distance:, **)
      return 0 if dates.none?
      (dates.count + 1 - (1 / distance.to_d))
    end

    def score_hash_for_activities(competition_activities, skip_ids: false)
      # dde_hash = dates_distance_elevation(competition_activities, skip_ids:)
      # dde_hash.merge(score: score_for(**dde_hash))
      dates_distance_elevation(competition_activities, skip_ids:)
    end

    private

    def dates_distance_elevation(competition_activities, skip_ids: false)
      if competition_activities.none?
        BLANK_SCORE.merge(skip_ids ? {} : {ids: []})
      elsif competition_activities.is_a?(ActiveRecord::Relation) # Active record collection
        {
          dates: competition_activities.included_dates_strings,
          distance: competition_activities.sum(:distance_meters), # skip _meters, for space saving
          elevation: competition_activities.sum(:elevation_meters) # skip _meters, for space saving
        }.merge(skip_ids ? {} : {ids: competition_activities.start_ordered.map(&:id)}) # Order IDs so they show up ordered
      else
        raise "competition_activities must be an ActiveRecord::Relation"
      end
    end
  end

  def current_competition?
    competition_id == Competition.current&.id
  end

  def excluded_from_competition?
    !included_in_competition
  end

  def distance_meters
    score_data&.dig("distance") || 0
  end

  def elevation_meters
    score_data&.dig("elevation") || 0
  end

  def activity_dates
    score_data&.dig("dates") || []
  end

  def included_activity_type?(activity_type)
    included_activity_types.include?(activity_type)
  end

  def set_calculated_attributes
    self.display_name ||= user&.display_name
    self.included_activity_types = if included_activity_types.blank?
      competition&.activity_types || Competition::DEFAULT_ACTIVITY_TYPES
    else
      included_activity_types.map(&:strip).reject(&:blank?)
    end.sort
    self.score = score_from_score_data
  end

  def update_score_data!
    update(score_data: calculated_score_data)
    reload
  end

  def calculated_score_data
    self.class.score_hash_for_activities(competition_activities_included, skip_ids: true)
      .merge(periods: competition.periods.map { |period| period.merge(period_score_hash(period)) })
      .as_json
  end

  private

  def score_from_score_data
    return 0 if score_data&.dig("dates").blank?
    self.class.score_for(dates: score_data["dates"], distance: score_data["distance"])
  end

  def period_score_hash(period)
    self.class.score_hash_for_activities(activities_for_period(period))
  end

  def activities_for_period(period)
    competition_activities_included.matching_dates_strings(
      Competition.dates_strings(period[:start_date], period[:end_date])
    )
  end
end

app/controllers/admin/competition_users_controller.rb
class Admin::CompetitionUsersController < Admin::BaseController
  include SortableTable

  before_action :set_period, only: [:index]
  before_action :find_competition_user, except: [:index]

  def index
    @competition_users = searched_competition_users
      .reorder("competition_users.#{sort_column} #{sort_direction}")
      .includes(:competition, :competition_activities)
  end

  def edit
  end

  def update
    if @competition_user.update(permitted_params)
      flash[:success] = "User updated"
      redirect_to(admin_competition_users_path, status: :see_other)
    else
      render :edit, status: :see_other
    end
  end

  private

  def sortable_columns
    %w[updated_at created_at email username]
  end

  def searched_competition_users
    competition_users = CompetitionUser
    if competition_subject.present?
      competition_users = competition_users.where(competition_id: competition_subject.id)
    end

    @time_range_column = (sort_column == "updated_at") ? "updated_at" : "created_at"
    competition_users.where(@time_range_column => @time_range)
  end

  def update_included_param
    params.permit(:update_included)
  end

  def permitted_params
    params.require(:competition_user).permit(:display_name, :included_in_competition)
  end

  def find_competition_user
    @competition_user = CompetitionUser.find(params[:id])
  end
end

app/views/admin/competition_users/edit.html.erb
<h1 class="mb-4">Edit User</h1>

<div class="row sm:grid-cols-2">
  <div class="col">
    <table class="table-list">
      <tbody>
        <tr>
          <td>Created</td>
          <td>
            <span class="convertTime"><%= l(@competition_user.created_at, format: :convert_time) %></span>
          </td>
        </tr>
        <tr>
          <td>Updated</td>
          <td>
            <small class="convertTime"><%= l(@competition_user.updated_at, format: :convert_time) %></small>
          </td>
        </tr>
        <tr>
          <td>Activities</td>
          <td>
            <%= number_display(@competition_user.competition_activities.count) %>
          </td>
        </tr>
        <tr>
          <td>Activities in competition</td>
          <td>
            <%= number_display(@competition_user.competition_activities.included_in_competition.count) %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col"></div>
</div>

<%= form_with(model: @competition_user, url: admin_competition_user_path(@competition_user), method: :patch, class: "mt-8 pb-2") do |f| %>
  <%= render partial: "/shared/errors", locals: {obj: @competition_user, name: "User"} %>

  <div class="row sm:grid-cols-2">
    <div class="col">
      <div class="mb-3">
        <%= f.label :display_name, class: "block mb-1 text-sm font-medium text-gray-900" %>
        <%= f.text_field :display_name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full max-w-80 p-2.5", required: true %>
      </div>
    </div>
    <div class="col">
      <div class="mb-3">
        <%= f.label :included_in_competition, class: "form-control-check" do %>
          <%= f.check_box :included_in_competition %>
          Included in competition?
        <% end %>
      </div>
    </div>
  </div>
  <div class="form-row-btn">
    <%= f.submit "save", class: "btn" %>
  </div>
<% end %>

app/views/admin/competition_users/index.html.erb
<h1 class="mb-4">
  Admin Competition Users
</h1>

<%= render(Admin::CurrentHeader::Component.new(viewing: controller_name.humanize, include_competition_select: true, competition_subject:, searchable_competitions:, render_period: false, s_params: sortable_params)) %>

<% skip_sortable ||= false %>
<% include_competition ||= competition_subject.blank? %>

<div class="full-screen-table mb-4">
  <table class="table table-sm table-bordered">
    <thead class="sortable">
      <tr>
        <th>
          <%= sortable "display_name", skip_sortable: skip_sortable %>
        </th>
        <th>
          <small><%= sortable "created_at", skip_sortable: skip_sortable %></small>
        </th>
        <% if include_competition %>
          <th>
            <%= sortable "competition_id", skip_sortable: skip_sortable %>
          </th>
        <% end %>
        <% if display_dev_info? %>
          <th>
            <small><%= sortable "updated_at", skip_sortable: skip_sortable %></small>
          </th>
        <% end %>
        <th>
          Activities
        </th>
        <th>Included?</th>
      </tr>
    </thead>
    <tbody>
      <% @competition_users.each do |competition_user| %>
        <tr class="odd:bg-white even:bg-gray-100">
          <td>
            <%= link_to competition_user.display_name, edit_admin_competition_user_path(competition_user), class: "base-link" %>
            <% if display_dev_info? %><code class="only-dev-visible-small"><%= competition_user.id %></code><% end %>
            <td>
              <span class="convertTime"><%= l(competition_user.created_at, format: :convert_time) %></span>
            </td>
            <% if include_competition %>
              <td>
                <%= competition_user.competition.display_name %>
              </td>
            <% end %>
            <% if display_dev_info? %>
              <td>
                <small class="convertTime"><%= l(competition_user.updated_at, format: :convert_time) %></small>
              </td>
            <% end %>
            <td><%= number_display(competition_user.competition_activities.count) %></td>
            <td class="table-cell-check">
              <%= check_mark if competition_user.included_in_competition %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>