config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "sessions"
  }

  root "landing#index"
  get "/update_strava", to: "landing#update_strava"

  resources :competitions, only: %i[show]

  resource :account, only: %i[edit update]

  namespace :admin do
    root to: "competition_users#index"
    resources :competitions, only: %i[index new create]
    resources :competition_users, only: %i[index edit update]
  end

  mount Lookbook::Engine, at: "/lookbook"

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <% if Rails.env.development? %>
      <link href="/favicon-dev.ico" rel="icon" sizes="192x192">
      <%= hotwire_livereload_tags %>
    <% else %>
      <link href="/favicon.ico" rel="icon" sizes="192x192">
      <link rel="apple-touch-icon-precomposed apple-touch-icon" href="/apple-touch-icon.png" />
    <% end %>
    <% unless display_dev_info? %>
      <style>
        .only-dev-visible {display: none !important;}
      </style>
    <% end %>
  </head>
  <body class="bg-white antialiased">
    <!--

    Source Code:

    github.com/MayIsBikeMonth/may_is_bike_month

  -->
    <ul class="relative z-10 flex items-center gap-4 px-2 lg:px-4 justify-end mt-1 mb-2">
      <% if current_user.blank? %>
        <li>
          <%= button_to "Sign in", user_strava_omniauth_authorize_path, method: :post, data: { turbo: false }, class: "base-link" %>
        </li>
      <% elsif in_admin? %>
        <span class="hidden sm:inline-block ml-2 text-lg font-semibold">May Is Bike Month Admin</span>
        <%= active_link "Competition Users", admin_competition_users_path, class: "base-link ml-2", match_controller: true %>
        <%= active_link "Competitions", admin_competitions_path, class: "base-link ml-2", match_controller: true %>
        <%= link_to "Exit", user_root_url, class: "base-link ml-auto less-strong" %>
      <% else %>
        <% if current_user.admin_access? %>
          <%= link_to "admin", admin_root_path, class: "mr-4 base-link" %>
        <% end %>
        <li>Hi <%= current_user.display_name %></li>
        <li>
          <%= button_to "logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "base-link"%>
        </li>

      <% end %>
    </ul>
    <%= render_flash_messages %>
    <div class="<%= @skip_wrapper_class ? "" : "wrapper-class" %>">
      <%= yield %>
    </div>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-63Y0BHVCS8"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-63Y0BHVCS8');
    </script>
  </body>
</html>

app/views/layouts/component_preview.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>May Is Bike Month</title>
    <%= stylesheet_link_tag "tailwind" %>
    <%= javascript_importmap_tags %>
    <%# This shouldn't be necessary - lookbook should live update :/ %>
    <% if Rails.env.development? %>
      <%= hotwire_livereload_tags %>
    <% end %>
  </head>
  <%# NOTE: This sets the theme %>
  <body class="<%= params.dig(:lookbook, :display, :theme) %>">
    <%# NOTE: at some point, make the padding optional %>
    <div class="w-full h-full p-4">
      <%= yield %>
    </div>
  </body>
</html>